### ISSUE TITLE
Add functionality to trigger function on URL route change

### ISSUE THREAD

**Issue by jubalm** [DarkFlorist/web3-app#40]
Would be handy to fire a function on route change like reconnecting or checking connected account

Example:
```mermaid
sequenceDiagram
    User->>App: Navigates to /tx/send
    App-->>User: Show send form
    User->>App: Submits Form
    App-)User: Redirect to /tx/[TRANSACTION_HASH]
    note left of App: run function to reconnect account
    App-)Chain: Send Transaction
    Chain-->>App: Confirm Transaction
    App-->>User: Show transaction receipt
    
```

**Comment by jubalm** [comment]
@MicahZoltu how do you feel about introducing [preact-router](https://www.npmjs.com/package/preact-router) instead of composing this ourselves? seems this has no dependencies

**Comment by MicahZoltu** [comment]
> @MicahZoltu how do you feel about introducing [preact-router](https://www.npmjs.com/package/preact-router) instead of composing this ourselves? seems this has no dependencies

Does it support hash based routing?  For statically hosted SPAs, path based routing doesn't work because the browser will try to fetch the page at `/path/to/route` which won't exist since everything is just a dumb statically hosted SPA.

**Comment by MicahZoltu** [comment]
Also, it is very cool that GitHub supports sequence diagrams!

**Comment by MicahZoltu** [comment]
Why do you need to reconnect account when the route changes?

**Comment by jubalm** [comment]
> Does it support hash based routing?

that will need history library then 🤔

> path based routing doesn't work because the browser will try to fetch the page at /path/to/route which won't exist since everything is just a dumb statically hosted SPA

i might be imagining things but doesn't IPFS has a redirect mechanism? that way setting `<base href='/' />` would correct the file references on a nested path?

> Why do you need to reconnect account when the route changes?

the dapp will reset it's states on reload/refresh. the dapp could then check if the wallet is unlocked and there's a connected account and reuse that instead of the user clicking connect again

**Comment by jubalm** [comment]
Closing in favor of custom hash routing #43 and reconnect #51 strategy
